# OpenWebUI V1의 메트릭 수집용 Service 정의
apiVersion: v1
kind: Service
metadata:
  name: openwebui-v1-metrics       # Prometheus ServiceMonitor가 참조할 서비스 이름
  namespace: default               # 네임스페이스
  labels:
    app: openwebui-v1              # 디플로이먼트와 일치해야 할 app 라벨
    metrics: "true"                # Prometheus 서비스 필터링용 커스텀 라벨
spec:
  selector:
    app: openwebui-v1              # 해당 디플로이먼트를 선택하는 라벨
  ports:
  - name: metrics                  # 포트 이름 (Prometheus에서 참조 가능)
    port: 9090                     # 서비스가 노출하는 포트 (Prometheus 기준)
    targetPort: 9090              # 실제 파드 내 컨테이너가 리스닝 중인 포트
---
# LiteLLM의 메트릭 수집용 Service 정의
apiVersion: v1
kind: Service
metadata:
  name: litellm-metrics
  namespace: default
  labels:
    app: litellm                   # 디플로이먼트의 라벨과 일치 필요
    metrics: "true"                # Prometheus가 label selector로 찾을 수 있도록
spec:
  selector:
    app: litellm                   # litellm 디플로이먼트 선택
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
