# PostgreSQL 데이터베이스를 실행하기 위한 StatefulSet 정의
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres                  # StatefulSet 이름
  namespace: default             # 네임스페이스 지정
spec:
  serviceName: postgres          # Stable DNS 주소를 위한 헤드리스 서비스 이름 (아래 정의된 서비스와 일치해야 함)
  replicas: 1                    # 복제 개수 (단일 노드)
  selector:
    matchLabels:
      app: postgres              # 파드 선택을 위한 라벨
  template:
    metadata:
      labels:
        app: postgres            # 위 selector와 일치하는 라벨
    spec:
      containers:
      - name: postgres           # 컨테이너 이름
        image: postgres:16       # PostgreSQL 16 버전 이미지 사용
        ports:
        - containerPort: 5432    # PostgreSQL 기본 포트
        env:                     # 환경 변수로 시크릿에서 DB 설정값을 주입
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata   # 데이터 디렉토리 지정
        resources:               # 컨테이너 리소스 요청/제한 설정
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:          # 컨테이너 생존 확인 프로브
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)  # 환경변수를 참조하여 유저로 접속 체크
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:         # 컨테이너 준비 여부 확인 프로브
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:           # PVC를 /var/lib/postgresql/data에 마운트
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:         # 파드별로 고유한 PVC를 생성하기 위한 템플릿
  - metadata:
      name: postgres-data       # 위 volumeMounts와 일치하는 이름
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp3     # EBS gp3 볼륨을 사용
      resources:
        requests:
          storage: 20Gi         # 파드당 20Gi 스토리지 요청
---
# PostgreSQL StatefulSet이 접근할 수 있도록 하는 클러스터 내부 서비스 정의
apiVersion: v1
kind: Service
metadata:
  name: postgres                 # StatefulSet에서 사용하는 serviceName과 일치
  namespace: default
spec:
  selector:
    app: postgres               # 파드를 선택하기 위한 라벨
  ports:
  - port: 5432                  # 서비스가 노출하는 포트
    targetPort: 5432            # 실제 파드에서 수신하는 포트
  type: ClusterIP               # 내부 접근만 허용하는 기본 서비스 타입
