apiVersion: apps/v1  # Deployment를 정의할 때 사용하는 API 버전
kind: Deployment  # 리소스 종류는 Deployment (파드를 관리하고 업데이트 자동화)
metadata:
  name: litellm  # Deployment 이름
  labels:
    app: litellm  # 라벨 지정 (서비스와 연동 등에서 사용)
spec:
  replicas: 1  # 파드 수 (1개 인스턴스만 실행)
  selector:
    matchLabels:
      app: litellm  # 이 라벨을 가진 파드를 관리 대상으로 지정
  template:
    metadata:
      labels:
        app: litellm  # 실제 생성될 파드에 적용될 라벨
    spec:
      containers:
      - name: litellm  # 컨테이너 이름
        image: ghcr.io/berriai/litellm:main-stable  # 사용할 Docker 이미지 (GitHub Container Registry에서 제공)
        ports:
        - containerPort: 4000  # 컨테이너 내부에서 열리는 포트 (외부와 연결될 포트)
        envFrom:
        - secretRef:
            name: litellm-env  # 환경변수를 불러올 secret 이름 (.env 파일을 기반으로 생성된 secret)
        volumeMounts:
        - name: config-volume  # 아래 volumes에서 정의한 볼륨과 연결
          mountPath: /app/config.yaml  # 컨테이너 내부에 마운트할 경로 (파일처럼 사용됨)
          subPath: config.yaml  # configMap의 단일 key를 파일로 마운트
        command:
          - "--host"            # 서버 실행 시 호스트 주소 지정
          - "0.0.0.0"           # 모든 IP로부터의 요청 허용
          - "--port"           
          - "4000"              # 서비스 포트 지정
          - "--config"
          - "/app/config.yaml"  # 마운트된 설정 파일 경로
          - "--detailed_debug"  # 디버깅 정보 활성화
      volumes:
      - name: config-volume  # 위에서 참조한 configMap 볼륨
        configMap:
          name: litellm-config  # 미리 생성된 ConfigMap 이름 (config.yaml이 들어 있음)
