name: Deploy to AWS EC2

on:
  push:
    branches:
      - deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: ./terraform-related/terraform_code_2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'ap-northeast-2' }}

      - name: Set Terraform .env content from Secrets
        run: echo "TF_VAR_env_file_content=${{ secrets.DOT_ENV_CONTENT }}" >> $GITHUB_ENV
        
      - name: Set docker-compose content as env var
        run: |
          echo "TF_VAR_docker_compose_content=$(base64 -w 0 docker-related/docker-compose.yml)" >> $GITHUB_ENV
      
      
      
      
      - name: Set litellm config content as env var
        run: |
            echo "TF_VAR_litellm_config_content=$(base64 -w 0 docker-related/litellm_config.yaml)" >> $GITHUB_ENV
        
      - name: Set prometheus config content as env var
        run: |
            echo "TF_VAR_prometheus_config_content=$(base64 -w 0 docker-related/prometheus_config/prometheus.yml)" >> $GITHUB_ENV
        
        
        
      
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file="terraform.tfvars" \
            -var="aws_region=${{ vars.AWS_REGION || 'ap-northeast-2' }}" \
            -var="ami_id=${{ vars.AMI_ID_UBUNTU_2004 }}" \
            -var="vpc_id=${{ vars.VPC_ID_DEV }}" \
            -var="subnet_id=${{ vars.SUBNET_ID_DEV }}" \
            -var="litellm_config_content=${{ env.TF_VAR_litellm_config_content }}" \
            -var="prometheus_config_content=${{ env.TF_VAR_prometheus_config_content }}" \
            -var="instance_name=llm-webui-host-${{ github.run_number }}" \
            -var="env_file_content=${{ secrets.DOT_ENV_CONTENT }}" \
            -var="docker_compose_content=${{ env.TF_VAR_docker_compose_content }}" \
            -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_env_file_content: ${{ secrets.DOT_ENV_CONTENT }}

      - name: Terraform Apply
        run: |
          terraform apply \
            -auto-approve \
            -var-file="terraform.tfvars" \
            -var="aws_region=${{ vars.AWS_REGION || 'ap-northeast-2' }}" \
            -var="ami_id=ami-0d5bb3742db8fc264" \
            -var="vpc_id=${{ vars.VPC_ID_DEV }}" \
            -var="subnet_id=${{ vars.SUBNET_ID_DEV }}" \
            -var="instance_name=llm-webui-host-${{ github.run_number }}" \
            -var="docker_compose_content=${{ env.TF_VAR_docker_compose_content }}" \
            -var="litellm_config_content=${{ env.TF_VAR_litellm_config_content }}" \
            -var="prometheus_config_content=${{ env.TF_VAR_prometheus_config_content }}" \
            -var="env_file_content=${{ secrets.DOT_ENV_CONTENT }}" \
            -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_openai_api_key: ${{ secrets.DOT_ENV_CONTENT }}
          


      