name: CI Build with .env from Secret

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env from GitHub Secret
        run: echo "${{ secrets.DOT_ENV_CONTENT }}" > .env

      - name: Build Docker image
        run: docker build -t openwebui-app .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy step (dummy)
        run: echo "🚀 Deploying openwebui-app..." 

